//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 06.06.2011 18:42:35
namespace Silverlight_Client.Services
{

    /// <summary>
    /// There are no comments for ConferenceContext in the schema.
    /// </summary>
    public partial class ConferenceContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ConferenceContext object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ConferenceContext(global::System.Uri serviceRoot) :
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Silverlight_Client.Services", typeName.Substring(5)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Silverlight_Client.Services", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Agendas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Conference> Agendas
        {
            get
            {
                if ((this._Agendas == null))
                {
                    this._Agendas = base.CreateQuery<Conference>("Agendas");
                }
                return this._Agendas;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Conference> _Agendas;
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Attendee> Attendees
        {
            get
            {
                if ((this._Attendees == null))
                {
                    this._Attendees = base.CreateQuery<Attendee>("Attendees");
                }
                return this._Attendees;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Attendee> _Attendees;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Session> Sessions
        {
            get
            {
                if ((this._Sessions == null))
                {
                    this._Sessions = base.CreateQuery<Session>("Sessions");
                }
                return this._Sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Session> _Sessions;
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Speaker> Speakers
        {
            get
            {
                if ((this._Speakers == null))
                {
                    this._Speakers = base.CreateQuery<Speaker>("Speakers");
                }
                return this._Speakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Speaker> _Speakers;
        /// <summary>
        /// There are no comments for Agendas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAgendas(Conference conference)
        {
            base.AddObject("Agendas", conference);
        }
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAttendees(Attendee attendee)
        {
            base.AddObject("Attendees", attendee);
        }
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSpeakers(Speaker speaker)
        {
            base.AddObject("Speakers", speaker);
        }
    }
    /// <summary>
    /// There are no comments for Model.Conference in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Agendas")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Conference : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Conference object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Conference CreateConference(int ID, string name, global::System.DateTime startDate, string endDate)
        {
            Conference conference = new Conference();
            conference.Id = ID;
            conference.Name = name;
            conference.StartDate = startDate;
            conference.EndDate = endDate;
            return conference;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this._EndDate = value;
                this.OnEndDateChanged();
                this.OnPropertyChanged("EndDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EndDate;
        partial void OnEndDateChanging(string value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                this._Speakers = value;
                this.OnPropertyChanged("Speakers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Speaker> _Speakers = new global::System.Data.Services.Client.DataServiceCollection<Speaker>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Attendee> Attendees
        {
            get
            {
                return this._Attendees;
            }
            set
            {
                this._Attendees = value;
                this.OnPropertyChanged("Attendees");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Attendee> _Attendees = new global::System.Data.Services.Client.DataServiceCollection<Attendee>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Attendee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Attendees")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Attendee : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Attendee object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Attendee CreateAttendee(int ID, string name)
        {
            Attendee attendee = new Attendee();
            attendee.Id = ID;
            attendee.Name = name;
            return attendee;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Agendas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Conference> Agendas
        {
            get
            {
                return this._Agendas;
            }
            set
            {
                this._Agendas = value;
                this.OnPropertyChanged("Agendas");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Conference> _Agendas = new global::System.Data.Services.Client.DataServiceCollection<Conference>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sessions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Session : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="startHour">Initial value of StartHour.</param>
        /// <param name="durationInMinutes">Initial value of DurationInMinutes.</param>
        /// <param name="day">Initial value of Day.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="track">Initial value of Track.</param>
        /// <param name="startMinute">Initial value of StartMinute.</param>
        /// <param name="capacity">Initial value of Capacity.</param>
        /// <param name="agenda_Id">Initial value of Agenda_Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Session CreateSession(int ID, string title, int startHour, int durationInMinutes, int day, string description, int track, int startMinute, int capacity, int agenda_Id)
        {
            Session session = new Session();
            session.Id = ID;
            session.Title = title;
            session.StartHour = startHour;
            session.DurationInMinutes = durationInMinutes;
            session.Day = day;
            session.Description = description;
            session.Track = track;
            session.StartMinute = startMinute;
            session.Capacity = capacity;
            session.Agenda_Id = agenda_Id;
            return session;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property StartHour in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StartHour
        {
            get
            {
                return this._StartHour;
            }
            set
            {
                this.OnStartHourChanging(value);
                this._StartHour = value;
                this.OnStartHourChanged();
                this.OnPropertyChanged("StartHour");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StartHour;
        partial void OnStartHourChanging(int value);
        partial void OnStartHourChanged();
        /// <summary>
        /// There are no comments for Property DurationInMinutes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DurationInMinutes
        {
            get
            {
                return this._DurationInMinutes;
            }
            set
            {
                this.OnDurationInMinutesChanging(value);
                this._DurationInMinutes = value;
                this.OnDurationInMinutesChanged();
                this.OnPropertyChanged("DurationInMinutes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DurationInMinutes;
        partial void OnDurationInMinutesChanging(int value);
        partial void OnDurationInMinutesChanged();
        /// <summary>
        /// There are no comments for Property Day in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Day
        {
            get
            {
                return this._Day;
            }
            set
            {
                this.OnDayChanging(value);
                this._Day = value;
                this.OnDayChanged();
                this.OnPropertyChanged("Day");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Day;
        partial void OnDayChanging(int value);
        partial void OnDayChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Track in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Track
        {
            get
            {
                return this._Track;
            }
            set
            {
                this.OnTrackChanging(value);
                this._Track = value;
                this.OnTrackChanged();
                this.OnPropertyChanged("Track");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Track;
        partial void OnTrackChanging(int value);
        partial void OnTrackChanged();
        /// <summary>
        /// There are no comments for Property StartMinute in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StartMinute
        {
            get
            {
                return this._StartMinute;
            }
            set
            {
                this.OnStartMinuteChanging(value);
                this._StartMinute = value;
                this.OnStartMinuteChanged();
                this.OnPropertyChanged("StartMinute");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StartMinute;
        partial void OnStartMinuteChanging(int value);
        partial void OnStartMinuteChanged();
        /// <summary>
        /// There are no comments for Property Capacity in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Capacity
        {
            get
            {
                return this._Capacity;
            }
            set
            {
                this.OnCapacityChanging(value);
                this._Capacity = value;
                this.OnCapacityChanged();
                this.OnPropertyChanged("Capacity");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Capacity;
        partial void OnCapacityChanging(int value);
        partial void OnCapacityChanged();
        /// <summary>
        /// There are no comments for Property Agenda_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Agenda_Id
        {
            get
            {
                return this._Agenda_Id;
            }
            set
            {
                this.OnAgenda_IdChanging(value);
                this._Agenda_Id = value;
                this.OnAgenda_IdChanged();
                this.OnPropertyChanged("Agenda_Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Agenda_Id;
        partial void OnAgenda_IdChanging(int value);
        partial void OnAgenda_IdChanged();
        /// <summary>
        /// There are no comments for Agenda in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Conference Agenda
        {
            get
            {
                return this._Agenda;
            }
            set
            {
                this._Agenda = value;
                this.OnPropertyChanged("Agenda");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Conference _Agenda;
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Attendee> Attendees
        {
            get
            {
                return this._Attendees;
            }
            set
            {
                this._Attendees = value;
                this.OnPropertyChanged("Attendees");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Attendee> _Attendees = new global::System.Data.Services.Client.DataServiceCollection<Attendee>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                this._Speakers = value;
                this.OnPropertyChanged("Speakers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Speaker> _Speakers = new global::System.Data.Services.Client.DataServiceCollection<Speaker>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Speaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Speakers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Speaker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Speaker object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="bio">Initial value of Bio.</param>
        /// <param name="photoUrl">Initial value of PhotoUrl.</param>
        /// <param name="agenda_Id">Initial value of Agenda_Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Speaker CreateSpeaker(int ID, string name, string bio, string photoUrl, int agenda_Id)
        {
            Speaker speaker = new Speaker();
            speaker.Id = ID;
            speaker.Name = name;
            speaker.Bio = bio;
            speaker.PhotoUrl = photoUrl;
            speaker.Agenda_Id = agenda_Id;
            return speaker;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Bio in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bio
        {
            get
            {
                return this._Bio;
            }
            set
            {
                this.OnBioChanging(value);
                this._Bio = value;
                this.OnBioChanged();
                this.OnPropertyChanged("Bio");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bio;
        partial void OnBioChanging(string value);
        partial void OnBioChanged();
        /// <summary>
        /// There are no comments for Property PhotoUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhotoUrl
        {
            get
            {
                return this._PhotoUrl;
            }
            set
            {
                this.OnPhotoUrlChanging(value);
                this._PhotoUrl = value;
                this.OnPhotoUrlChanged();
                this.OnPropertyChanged("PhotoUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhotoUrl;
        partial void OnPhotoUrlChanging(string value);
        partial void OnPhotoUrlChanged();
        /// <summary>
        /// There are no comments for Property Agenda_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Agenda_Id
        {
            get
            {
                return this._Agenda_Id;
            }
            set
            {
                this.OnAgenda_IdChanging(value);
                this._Agenda_Id = value;
                this.OnAgenda_IdChanged();
                this.OnPropertyChanged("Agenda_Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Agenda_Id;
        partial void OnAgenda_IdChanging(int value);
        partial void OnAgenda_IdChanged();
        /// <summary>
        /// There are no comments for Agenda in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Conference Agenda
        {
            get
            {
                return this._Agenda;
            }
            set
            {
                this._Agenda = value;
                this.OnPropertyChanged("Agenda");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Conference _Agenda;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
